Feat/eos core explain
fariedt/BitGoJS pull request #38
Opened 2021-07-13 08:49 UTC by gibrangul95

@fdmirza explain transaction implementation and tests

2021-07-15 07:45 UTC, fdmirza requested changes

2021-07-15 07:45 UTC, fdmirza commented on modules/account-lib/src/coin/eos/transaction.ts
> +      if (action.name === 'transfer') {
What will be inputs/outputs for other actions?

2021-07-15 07:45 UTC, fdmirza commented on modules/account-lib/src/coin/eos/transaction.ts
> +  async loadInputsAndOutputs(): Promise<void> {
are we covering this in tests?

2021-07-15 07:45 UTC, fdmirza commented on modules/account-lib/src/coin/eos/transaction.ts
> +  async loadInputsAndOutputs(): Promise<void> {
Where is this method `loadInputsAndOutputs` used ?

2021-07-15 07:51 UTC, gibrangul95 commented on modules/account-lib/src/coin/eos/transaction.ts
> +  async loadInputsAndOutputs(): Promise<void> {
its not actually being used anywhere, the format of the transaction._outputs is different from that of explain transaction. Based on the current code we could remove this function.

2021-07-16 10:08 UTC, fdmirza approved these changes

2021-07-16 10:09 UTC, merged